northwind_traders_elt:
  target: "{{ env_var('DBT_DEFAULT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: databricks
      threads: 8
      schema: "{{ env_var('DEV_SCHEMA_NAME') }}"
      catalog: "{{ env_var('DEV_DATABRICKS_CATALOG') }}"
      host: "{{ env_var('DEV_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DEV_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DEV_DATABRICKS_TOKEN') }}"
      ansi_mode: false


    prod:
      type: databricks
      threads: 8
      schema: "{{ env_var('PROD_SCHEMA_NAME') }}"
      catalog: "{{ env_var('PROD_DATABRICKS_CATALOG') }}"
      host: "{{ env_var('PROD_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('PROD_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('PROD_DATABRICKS_TOKEN') }}"
      ansi_mode: false